global:
  scrape_interval: 5s

scrape_configs:
  - job_name: Prometheus
    static_configs:
      - targets: ["prometheus:9090"]
  
  - job_name: 'test_api'
    static_configs:
      - targets: ['192.168.0.101:45456'] 
    metrics_path: /metrics-text   
    
# Add other services here
